### PR TITLE
Revert "Update lab1.java"

### PR DESCRIPTION
**Pull request by ahuang-cs**
Reverts ahuang-cs/CISC191#17

Please do not commit source code to this class github. The only artifacts that should be uploaded are your jars.

### CODE REVIEW

**Comment by chrisfisher1993** [comment]
Professor,

I'm trying to complete lab 1 and I've followed the videos you posted but im
still having issues in the input inside the terminal via putty.

**Comment by ahuang-cs** [comment]
Hi Chris,

I haven't finished the videos yet, but see my response to Riles about the commands to upload jars on the Q&A page: https://urldefense.proofpoint.com/v2/url?u=https-3A__sdccd.instructure.com_courses_2382940_discussion-5Ftopics_14079935&d=DwIF-g&c=Nk1UtDBliM_fW3DCK8CoTNhFqaER3tCmN6o4Lel0Rw4&r=fMP8a-dLNP5qxWAz1Z_F_SN6pESl4EcazVGLoPu3dmhA3u41Ll9Ij1Vs5Ogjmw6BGBsKoeqkX7xsNah5C94alIfFtt59Sr434L5Uem7n2A4&m=GRhDepfC_D38wCV5SsjjGVJElSKcqRXUVC9PKvEQf64&s=CSBCjfHXGYS5qgYtm93TFZHc5nzkrOEdILy1r48SGKc&e= 

________________________________

**Comment by chrisfisher1993** [comment]
Professor,

I am still struggling with lab 1. I am up to this point but can't get
the version control part down to open the cisc191 github in intellij.
I couldnt figure out to send a screen shot on canvas so I attached it
in this email instead.

Appreciate any help.

Chris Fisher

**Comment by ahuang-cs** [comment]
Hi Chris,
Unfortunately, I don't see an attachment in this image either. Can you copy and paste the console output?

________________________________

**Comment by chrisfisher1993** [comment]
I haven't gotten that far yet. I'm still unable to open the cisc191github
in intellij. I copied the gitclone but I think I have a different pathway.

**Comment by ahuang-cs** [comment]
I can't really help if you don't give me some errors or output to look at. I would recommend following the video tutorial. With Amazon, its easy to start over from scratch.

________________________________

**Comment by chrisfisher1993** [comment]
Professor,

I changed the image to a jpeg I cannot get the github CISC191 to work
in intellij. I'm gonna retry from scratch again. I've followed along
with the videos multiple times but, have had no luck completing lab 1.
Is there any way I can get instruction in person? I've worked with
other classmates in your class to complete this lab and all of us are
quite lost in regards to the things you've asked of us for this week.

Any help is appreciated.

Chris Fisher

**Comment by chrisfisher1993** [comment]
Another problem I had with the tigervnc setup

**Comment by ahuang-cs** [comment]
I'm still not seeing any images. Are you using mac? Maybe try https://urldefense.proofpoint.com/v2/url?u=https-3A__sourceforge.net_projects_chicken_&d=DwIF-g&c=Nk1UtDBliM_fW3DCK8CoTNhFqaER3tCmN6o4Lel0Rw4&r=BJWJyUtfV11LXnflkmo_Xwb9A7ZO5B9ADrkH4UpDhuNuZQ5LKCZaZuZKncwRX8_B_9j-W6PgTQVVDYETPxetQzSBiSFxaalqu5fkPtmHcjc&m=D_Ji8G2fiilW5AcSAiOKHxeF7ZFR0hqUcHKLJ56xvN4&s=1qj5HTgcCAl1tylMgmgQE8PIeLUU7-I-NbqcKoz0QAw&e= , instead of TigerVNC.

________________________________

**Comment by chrisfisher1993** [comment]
Professor,

Is there any way to work on module 2 this week? I thought that classes
were suspended for this week so we'd have time to get caught up.
Otherwise should we just work on module 3?

Chris Fisher

**Comment by ahuang-cs** [comment]
Hi Chris,
The school closure actually started today, so it did not affect module 2's deadline of yesterday at midnight. Module 3 deadlines will be extended until the following week to account for the closure.

________________________________

**Comment by Rafonsi** [comment]
Professor, does this include lab 3?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by ahuang-cs** [comment]
Oh right, Lab3 is extended until the following Tuesday.

________________________________

**Pull request merged**
